gencode_gene:
  adapter:
    module: biocypher_metta.adapters.gencode_gene_adapter
    cls: GencodeGeneAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/gencode/gencode.annotation.gtf.gz
      gene_alias_file_path: ./aux_files/Homo_sapiens.gene_info.gz
  outdir: gencode/gene
  nodes: True
  edges: False

gencode_transcripts:
  adapter:
    module: biocypher_metta.adapters.gencode_adapter
    cls: GencodeAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/gencode/gencode.annotation.gtf.gz
      type: transcript
      label: transcript
  outdir: gencode/transcript
  nodes: True
  edges: False

transcribed_to:
  adapter:
    module: biocypher_metta.adapters.gencode_adapter
    cls: GencodeAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/gencode/gencode.annotation.gtf.gz
      type: transcribed to
      label: transcribed_to
  outdir: gencode/transcript
  nodes: False
  edges: True

transcribed_from:
  adapter:
    module: biocypher_metta.adapters.gencode_adapter
    cls: GencodeAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/gencode/gencode.annotation.gtf.gz
      type: transcribed from
      label: transcribed_from
  outdir: gencode/transcript
  nodes: False
  edges: True

uniprotkb_sprot:
  adapter:
    module: biocypher_metta.adapters.uniprot_protein_adapter
    cls: UniprotProteinAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/uniprot/uniprot_sprot_human.dat.gz
  outdir: uniprot
  nodes: True
  edges: False

uniprotkb_sprot_translates_to:
  adapter:
    module: biocypher_metta.adapters.uniprot_adapter
    cls: UniprotAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/uniprot/uniprot_sprot_human.dat.gz
      type: translates to
      label: translates_to
  outdir: uniprot
  nodes: False
  edges: True

uniprotkb_sprot_translates_of:
  adapter:
    module: biocypher_metta.adapters.uniprot_adapter
    cls: UniprotAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/uniprot/uniprot_sprot_human.dat.gz
      type: translation of
      label: translation_of
  outdir: uniprot
  nodes: False
  edges: True

pathway:
  adapter:
    module: biocypher_metta.adapters.reactome_pathway_adapter
    cls: ReactomePathwayAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/reactome/ReactomePathways.txt
      pubmed_map_path: /mnt/hdd_2/abdu/biocypher_data/reactome/ReactionPMIDS.txt
  outdir: reactome
  nodes: True
  edges: False

genes_pathways:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/reactome/Ensembl2Reactome_All_Levels.txt
      label: genes_pathways
  outdir: reactome
  nodes: False
  edges: True

parent_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/reactome/ReactomePathwaysRelation.txt
      label: parent_pathway_of
  outdir: reactome
  nodes: False
  edges: True

child_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/reactome/ReactomePathwaysRelation.txt
      label: child_pathway_of
  outdir: reactome
  nodes: False
  edges: True

go_biological_process:
  adapter:
    module: biocypher_metta.adapters.gene_ontology_adapter
    cls: GeneOntologyAdapter
    args:
      ontology: 'go'
      type: node
      label: biological_process
      dry_run: False
      add_description: False
      cache_dir: ./ontology_dataset_cache
  outdir: gene_ontology/biological_process
  nodes: True
  edges: False

go_biological_process_subclass_of:
  adapter:
    module: biocypher_metta.adapters.gene_ontology_adapter
    cls: GeneOntologyAdapter
    args:
      ontology: 'go'
      type: edge
      label: biological_process_subclass_of
      dry_run: False
      cache_dir: ./ontology_dataset_cache
  outdir: gene_ontology/biological_process
  nodes: False
  edges: True

go_molecular_function:
  adapter:
    module: biocypher_metta.adapters.gene_ontology_adapter
    cls: GeneOntologyAdapter
    args:
      ontology: 'go'
      type: node
      label: molecular_function
      dry_run: False
      add_description: False
      cache_dir: ./ontology_dataset_cache
  outdir: gene_ontology/molecular_function
  nodes: True
  edges: False

go_molecular_function_subclass_of:
  adapter:
    module: biocypher_metta.adapters.gene_ontology_adapter
    cls: GeneOntologyAdapter
    args:
      ontology: 'go'
      type: edge
      label: molecular_function_subclass_of
      dry_run: False
      cache_dir: ./ontology_dataset_cache
  outdir: gene_ontology/molecular_function
  nodes: False
  edges: True

go_cellular_component:
  adapter:
    module: biocypher_metta.adapters.gene_ontology_adapter
    cls: GeneOntologyAdapter
    args:
      ontology: 'go'
      type: node
      label: cellular_component
      dry_run: False
      add_description: False
      cache_dir: ./ontology_dataset_cache
  outdir: gene_ontology/cellular_component
  nodes: True
  edges: False

go_cellular_component_subclass_of:
  adapter:
    module: biocypher_metta.adapters.gene_ontology_adapter
    cls: GeneOntologyAdapter
    args:
      ontology: 'go'
      type: edge
      label: cellular_component_subclass_of
      dry_run: False
      cache_dir: ./ontology_dataset_cache
  outdir: gene_ontology/cellular_component
  nodes: False
  edges: True

gaf_biological_process_gene_product:
  adapter:
    module: biocypher_metta.adapters.gaf_adapter
    cls: GAFAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/go/goa_human.gaf.gz
      label: biological_process_gene_product
  outdir: gaf
  nodes: False
  edges: True

gaf_molecular_function_gene_product:
  adapter:
    module: biocypher_metta.adapters.gaf_adapter
    cls: GAFAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/go/goa_human.gaf.gz
      label: molecular_function_gene_product
  outdir: gaf
  nodes: False
  edges: True

gaf_cellular_component_gene_product_part_of:
  adapter:
    module: biocypher_metta.adapters.gaf_adapter
    cls: GAFAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/go/goa_human.gaf.gz
      label: cellular_component_gene_product_part_of
  outdir: gaf
  nodes: False
  edges: True

gaf_cellular_component_gene_product_located_in:
  adapter:
    module: biocypher_metta.adapters.gaf_adapter
    cls: GAFAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/go/goa_human.gaf.gz
      label: cellular_component_gene_product_located_in
  outdir: gaf
  nodes: False
  edges: True

coexpression:
  adapter:
    module: biocypher_metta.adapters.coxpresdb_adapter
    cls: CoxpresdbAdapter
    args:
      filepath: ./samples/coxpressdb
      ensemble_to_entrez_path: ./aux_files/entrez_to_ensembl.pkl
  outdir: coxpressdb
  nodes: False
  edges: True

tflink:
  adapter:
    module: biocypher_metta.adapters.tflink_adapter
    cls: TFLinkAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/tf_links/tf_links.csv
  outdir: tf_links
  nodes: False
  edges: True

string_ppi:
  adapter:
    module: biocypher_metta.adapters.string_ppi_adapter
    cls: StringPPIAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/string_ppi/9606.protein.links.detailed.v11.5.txt.gz
  outdir: string_ppi
  nodes: False
  edges: True

tadmap:
  adapter:
    module: biocypher_metta.adapters.tadmap_adapter
    cls: TADMapAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/tadmap/tadmap_v1_hg38.txt
  outdir: tadmap
  nodes: False
  edges: True

hocomoco:
  adapter:
    module: biocypher_metta.adapters.hocomoco_adapter
    cls: HoCoMoCoAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/hocomoco/hocomoco_motifs.txt
  outdir: hocomoco
  nodes: False
  edges: True

roadmap_chromatin_states:
  adapter:
    module: biocypher_metta.adapters.roadmap_chromatin_state_adapter
    cls: RoadmapChromatinStateAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/roadmap/roadmap_data_hg38.tsv
  outdir: roadmap_chromatin
  nodes: False
  edges: True

gtex_eqtl_expression:
  adapter:
    module: biocypher_metta.adapters.gtex_adapter
    cls: GTExAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/gtex/gtex_expression.txt
      tissue: all
  outdir: gtex
  nodes: True
  edges: False

gencode_exon:
  adapter:
    module: biocypher_metta.adapters.gencode_exon_adapter
    cls: GencodeExonAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/gencode/gencode.annotation.gtf.gz
  outdir: gencode/exon
  nodes: True
  edges: False

transcript_includes_exon:
  adapter:
    module: biocypher_metta.adapters.gencode_exon_adapter
    cls: GencodeExonAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/gencode/gencode.annotation.gtf.gz
      label: includes
  outdir: gencode/exon
  nodes: False
  edges: True

rna_central_non_coding_rna:
  adapter:
    module: biocypher_metta.adapters.rna_central_adapter
    cls: RNACentralAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/rna_central/homo_sapiens.GRCh38.bed.gz
      rfam_filepath: /mnt/hdd_2/abdu/biocypher_data/rna_central/rnacentral_rfam_annotations.tsv.gz
      label: non_coding_rna
      type: non_coding_rna
  outdir: rna_central
  nodes: True
  edges: False

rna_central_non_coding_rna_biological_process:
  adapter:
    module: biocypher_metta.adapters.rna_central_adapter
    cls: RNACentralAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/rna_central/sample_homo_sapiens.GRCh38.bed.gz
      rfam_filepath: /mnt/hdd_2/abdu/biocypher_data/rna_central/sample_rnacentral_rfam_annotations.tsv.gz
      type: biological process rna
      label: biological_process_rna
  outdir: rna_central
  nodes: False
  edges: True  

rna_central_non_coding_rna_molecular_function:
  adapter:
    module: biocypher_metta.adapters.rna_central_adapter
    cls: RNACentralAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/rna_central/sample_homo_sapiens.GRCh38.bed.gz
      rfam_filepath: /mnt/hdd_2/abdu/biocypher_data/rna_central/sample_rnacentral_rfam_annotations.tsv.gz
      type: molecular function rna
      label: molecular_function_rna
  outdir: rna_central
  nodes: False
  edges: True  

rna_central_non_coding_rna_cellular_component:
  adapter:
    module: biocypher_metta.adapters.rna_central_adapter
    cls: RNACentralAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/rna_central/sample_homo_sapiens.GRCh38.bed.gz
      rfam_filepath: /mnt/hdd_2/abdu/biocypher_data/rna_central/sample_rnacentral_rfam_annotations.tsv.gz
      type: cellular component rna
      label: cellular_component_rna
  outdir: rna_central
  nodes: False
  edges: True   

dgv_variant:
  adapter:
    module: biocypher_metta.adapters.dgv_variant_adapter
    cls: DGVVariantAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/dgv/GRCh38_hg38_variants_2020-02-25.txt.gz
  outdir: dgv
  nodes: True
  edges: False

epd_promoter:
  adapter:
    module: biocypher_metta.adapters.epd_adapter
    cls: EPDAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/epd/Hs_EPDnew.bed.gz
      hgnc_to_ensembl_map: ./aux_files/hgnc_to_ensembl.pkl
  outdir: epd
  nodes: True
  edges: False

epd_promoter_regulates_gene:
  adapter:
    module: biocypher_metta.adapters.epd_adapter
    cls: EPDAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/epd/Hs_EPDnew.bed.gz
      hgnc_to_ensembl_map: ./aux_files/hgnc_to_ensembl.pkl
      type: promoter to gene association
      label: promoter_gene
  outdir: epd
  nodes: False
  edges: True

dbvar_variant:
  adapter:
    module: biocypher_metta.adapters.dbvar_adapter
    cls: DBVarVariantAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/dbvar/GRCh38.variant_call.all.vcf.gz
  outdir: dbvar
  nodes: True
  edges: False

peregrine_enhancer:
  adapter:
    module: biocypher_metta.adapters.peregrine_adapter
    cls: PEREGRINEAdapter
    args:
      enhancers_file: /mnt/hdd_2/abdu/biocypher_data/peregrine/PEREGRINEenhancershg38.gz
      enhancer_gene_link: /mnt/hdd_2/abdu/biocypher_data/peregrine/enhancer_gene_link_18.tsv.gz
      source_file: /mnt/hdd_2/abdu/biocypher_data/peregrine/PEREGRINEenhancersources.gz
      hgnc_ensembl_map: ./aux_files/hgnc_ensembl_map.pkl
      tissue_ontology_map: ./aux_files/peregrine_tissues_to_ontology_map.pkl
  outdir: peregrine
  nodes: True
  edges: False

peregrine_enhancer_regulates:
  adapter:
    module: biocypher_metta.adapters.peregrine_adapter
    cls: PEREGRINEAdapter
    args:
      enhancers_file: /mnt/hdd_2/abdu/biocypher_data/peregrine/PEREGRINEenhancershg38.gz
      enhancer_gene_link: /mnt/hdd_2/abdu/biocypher_data/peregrine/enhancer_gene_link_18.tsv.gz
      source_file: /mnt/hdd_2/abdu/biocypher_data/peregrine/PEREGRINEenhancersources.gz
      hgnc_ensembl_map: ./aux_files/hgnc_ensembl_map.pkl
      tissue_ontology_map: ./aux_files/peregrine_tissues_to_ontology_map.pkl
      type: enhancer to gene association
      label: enhancer_gene
  outdir: peregrine
  nodes: False
  edges: True

# Ensure paths are correctly formatted and accessible
dbsuper_super_enhancer:
  adapter:
    module: biocypher_metta.adapters.dbsuper_adapter
    cls: DBSuperAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/dbsuper/dbSUPER_SuperEnhancers_hg19.tsv.gz
      hgnc_to_ensembl_map: ./aux_files/hgnc_to_ensembl.pkl
      dbsuper_tissues_map: ./aux_files/dbsuper_tissues_map.pkl
  outdir: dbsuper
  nodes: True
  edges: False

dbsuper_super_enhancer_regulates_gene:
  adapter:
    module: biocypher_metta.adapters.dbsuper_adapter
    cls: DBSuperAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/dbsuper/dbSUPER_SuperEnhancers_hg19.tsv.gz
      hgnc_to_ensembl_map: ./aux_files/hgnc_to_ensembl.pkl
      dbsuper_tissues_map: ./aux_files/dbsuper_tissues_map.pkl
      type: super enhancer to gene association
      label: super_enhancer_gene
  outdir: dbsuper
  nodes: False
  edges: True

dbsnp_snps:
  adapter:
    module: biocypher_metta.adapters.dbsnp_adapter
    cls: DBSNPAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/dbsnp/dbSNP_158.GRCh38.vcf.gz
  outdir: dbsnp
  nodes: True
  edges: False

